version: '3.8'

services:

  db:
    container_name: 0auth_back_end_postgresql_database
    image: postgres:12.3-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testDB3
      POSTGRES_USER: userDB3
      POSTGRES_PASSWORD: userDB3